# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-06 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vid',
            name='inputVid',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='vid',
            name='outputVid',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
